name = "Legal Pages Generator"
client_id = "de5ea8a617948c0065ea7740ac0650d2"
application_url = "https://legal-pages-generator.vercel.app"
embedded = true

[access_scopes]
scopes = "read_online_store_pages,write_online_store_pages"

[auth]
redirect_urls = [
  "https://legal-pages-generator.vercel.app/auth/callback"
]

webhooks: {
  APP_UNINSTALLED: {
    deliveryMethod: DeliveryMethod.Http,
    callbackUrl: "https://legal-pages-generator.vercel.app/webhooks",
  },
  CUSTOMERS_DATA_REQUEST: {
    deliveryMethod: DeliveryMethod.Http,
    callbackUrl: "https://legal-pages-generator.vercel.app/webhooks",
  },
  CUSTOMERS_REDACT: {
    deliveryMethod: DeliveryMethod.Http,
    callbackUrl: "https://legal-pages-generator.vercel.app/webhooks",
  },
  SHOP_REDACT: {
    deliveryMethod: DeliveryMethod.Http,
    callbackUrl: "https://legal-pages-generator.vercel.app/webhooks",
  },
},

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
