# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration
client_id = "de5ea8a617948c0065ea7740ac0650d2"
name = "Legal Pages Generator"
application_url = "https://legal-pages-generator.vercel.app/"
embedded = true

[webhooks]
api_version = "2026-01"

[[webhooks.subscriptions]]
compliance_topics = ["customers/data_request", "customers/redact", "shop/redact"]
uri = "/webhooks"

[access_scopes]
scopes = "read_online_store_pages,write_online_store_pages"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [ "https://legal-pages-generator.vercel.app/auth/callback" ]