client_id = "257601e523745b5ee78de012d18c8520"
name = "Legal Pages Generator"
application_url = "https://legal-pages-generator.vercel.app"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-01"

[[webhooks.subscriptions]]
compliance_topics = ["customers/data_request", "customers/redact", "shop/redact"]
uri = "/webhooks"

[access_scopes]
scopes = "read_online_store_pages,write_online_store_pages"

[auth]
redirect_urls = [
  "https://legal-pages-generator.vercel.app/auth/callback"
]