# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "0265ac2054b840dc01bdfd33c3ccb694"
name = "Legal Pages Generator"
application_url = "https://example.com"
embedded = true

[webhooks]
api_version = "2026-04"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_online_store_pages,write_online_store_pages"

[auth]
redirect_urls = [ "https://example.com/api/auth" ]
